/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "assignment.h"

outData* registerRequest(inData *register_1_arg, CLIENT *clnt );
outData* loginRequest(inData *login_1_arg, CLIENT *clnt);

void
add_prog_1(char *host)
{
	CLIENT *clnt;
	outData  *result_1;
	inData  register_1_arg;
	outData  *result_2;
	//inData  login_1_arg;

#ifndef	DEBUG
	clnt = clnt_create (host, ADD_PROG, ADD_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
// Neeraj Start
	int value = 1;
	char* userName;
	char* password;
	char str[20],c=' ';
	int i = 0;

	printf("\n1. Register\n2. Login");
	printf("\nPlease provide your choice: ");
	scanf("%d", &register_1_arg.mode);
	if(register_1_arg.mode != 1 && register_1_arg.mode != 2) {
		printf("\nSorry, you have choosen wrong input.\n");
	} 
	else {
		printf("Enter the username: ");	
		scanf("%s", &register_1_arg.user);
		printf("Enter the password: ");
		scanf("%s", &register_1_arg.pass);
		if(register_1_arg.mode == 1) {
			result_1 = registerRequest(&register_1_arg, clnt);
			if (result_1 == (outData *) NULL) {
				clnt_perror (clnt, "call failed");
			}
			else {
				if(result_1->rCode == 1){
					char input;
					printf("\nDo you want to login[y/n]?");
					scanf(" %c", &input);
					if(input == 'y') {
						result_2 = loginRequest(&register_1_arg, clnt);
					}
				}
			}
		}
		else if(register_1_arg.mode == 2) {
			result_2 = loginRequest(&register_1_arg, clnt);
			if (result_2 == (outData *) NULL) {
				clnt_perror (clnt, "call failed");
			}
		}
		
		
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}

outData* registerRequest(inData *register_1_arg, CLIENT *clnt )
{
	outData* result_1 = register_1(register_1_arg, clnt);
	if (result_1 == (outData *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("%s", result_1->rString);
	}
	return result_1;
}

outData* loginRequest(inData *login_1_arg, CLIENT *clnt)
{
	outData* result_2 = login_1(login_1_arg, clnt);
	if (result_2 == (outData *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	else {
		printf("%s", result_2->rString);
	}
	return result_2;
}

int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	add_prog_1 (host);
exit (0);
}
