/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _ASSIGNMENT_H_RPCGEN
#define _ASSIGNMENT_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct inData {
	int mode;
	char user[256];
	char pass[256];
};
typedef struct inData inData;

struct outData {
	int rCode;
	char rString[256];
};
typedef struct outData outData;

#define ADD_PROG 0x33451111
#define ADD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define REGISTER 1
extern  outData * register_1(inData *, CLIENT *);
extern  outData * register_1_svc(inData *, struct svc_req *);
#define LOGIN 2
extern  outData * login_1(inData *, CLIENT *);
extern  outData * login_1_svc(inData *, struct svc_req *);
extern int add_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define REGISTER 1
extern  outData * register_1();
extern  outData * register_1_svc();
#define LOGIN 2
extern  outData * login_1();
extern  outData * login_1_svc();
extern int add_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_inData (XDR *, inData*);
extern  bool_t xdr_outData (XDR *, outData*);

#else /* K&R C */
extern bool_t xdr_inData ();
extern bool_t xdr_outData ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_ASSIGNMENT_H_RPCGEN */
